spring:
  profiles:
    active: dev
---
server:
  port: 12800

spring:
  profiles: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql.eleven.nowy.xyz:3306/eleven_system?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:eleven_system}
    password: ${SPRING_DATASOURCE_PASSWORD:eleven_system}
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://mysql.eleven.nowy.xyz:3306/eleven_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: eleven_system
    password: eleven_system
